Layout/FirstArrayElementIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/LineLength:
  Max: 100

Naming/FileName:
  Exclude:
    - increments-schedule.gemspec

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
