Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
